on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build and tag Docker image
        run: |
          docker build -t department-service:v1 .


  deploy:
    env:
      APP_PORT: ${{ secrets.APP_PORT }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    runs-on: [self-hosted]
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Stop and Remove Existing Containers
        run: docker compose down || true  # Ignore errors if no containers are running

      - name: Run with Docker Compose
        run: docker compose up -d
